# Generated by Django 2.1.5 on 2021-07-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketInfo',
            fields=[
                ('packet_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('frame_time', models.CharField(max_length=50)),
                ('eth_src', models.CharField(blank=True, max_length=20, null=True)),
                ('eth_dst', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_src', models.CharField(blank=True, max_length=16, null=True)),
                ('ip_dst', models.CharField(blank=True, max_length=16, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=20)),
                ('ip_len', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PcapInfo',
            fields=[
                ('pcap_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('pcap_name', models.CharField(max_length=120)),
                ('pcap_url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packetinfo',
            name='pcap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapinspector.PcapInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='pcapinfo',
            unique_together={('pcap_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='packetinfo',
            unique_together={('frame_number', 'pcap')},
        ),
    ]
