# Generated by Django 2.1.5 on 2021-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pcap_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.CharField(max_length=10)),
                ('frame_time', models.DateTimeField()),
                ('eth_src', models.CharField(max_length=20)),
                ('eth_dst', models.CharField(max_length=20)),
                ('ip_src', models.CharField(max_length=16)),
                ('ip_dst', models.CharField(max_length=16)),
                ('src_port', models.IntegerField(max_length=5)),
                ('dst_port', models.IntegerField(max_length=5)),
                ('ttl', models.IntegerField(max_length=3)),
                ('protocol', models.CharField(max_length=20)),
                ('ip_len', models.IntegerField(max_length=10)),
            ],
        ),
    ]
