# Generated by Django 2.1.5 on 2021-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcap_result',
            name='dst_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='ip_len',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='src_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='ttl',
            field=models.IntegerField(),
        ),
    ]
