# Generated by Django 2.1.5 on 2021-05-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0002_auto_20210522_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcap_result',
            name='id',
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='dst_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='frame_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pcap_result',
            name='src_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
