# Generated by Django 2.1.5 on 2021-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0003_auto_20210523_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcap_result',
            name='frame_time',
            field=models.CharField(max_length=50),
        ),
    ]
