# Generated by Django 2.1.5 on 2021-06-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0004_auto_20210523_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pcap_result',
            new_name='PcapInfo',
        ),
    ]
