# Generated by Django 2.1.5 on 2021-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0005_auto_20210612_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapinfo',
            name='ip_dst',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='ip_src',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
