# Generated by Django 2.1.5 on 2021-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0006_auto_20210612_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapinfo',
            name='eth_dst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='eth_src',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='ip_dst',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='ip_len',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='ip_src',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pcapinfo',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
