# Generated by Django 2.1.5 on 2021-06-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapinspector', '0007_auto_20210612_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapinfo',
            name='frame_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
